language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install matplotlib
  - pip install .

# command to install dependencies
script: 
    - python tests/test_filterbank.py
    - python tests/test_guppi.py
    
branches:
  only:
    - master
