language: python
matrix:
  include:
  - env: DIST=py2_kern.docker
  - env: DIST=py2_manual.docker
  - env: DIST=py3_kern.docker
  - env: DIST=py3_manual.docker
services:
- docker
before_install:
- true
install:
- docker build . -t ${DIST} -f docker/${DIST}
- pip install coveralls
before_script:
- true
script:
- true
after_success:
- coveralls
